-- MySQL Script generated by MySQL Workbench
-- Thu Apr 19 11:41:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdbanco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdbanco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdbanco` DEFAULT CHARACTER SET utf8 ;
USE `bdbanco` ;

-- -----------------------------------------------------
-- Table `bdbanco`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdbanco`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `Dni` VARCHAR(50) NULL,
  `Contrasena` VARCHAR(50) NULL DEFAULT NULL,
  `Nombre` VARCHAR(50) NULL DEFAULT NULL,
  `Apellidos` VARCHAR(50) NULL DEFAULT NULL,
  `Telefono` INT(11) NULL DEFAULT NULL,
  `Email` VARCHAR(50) NULL DEFAULT NULL,
  `Domicilio` VARCHAR(50) NULL DEFAULT NULL,
  `Cuenta` INT(11) NULL DEFAULT NULL,
  `Saldo` DOUBLE NULL DEFAULT NULL,
  `Estado` TINYINT(4) NULL DEFAULT NULL,
  `Empleado` TINYINT(4) NULL DEFAULT NULL,
  `usuario_idUsuario` INT(11) NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_usuario1_idx` (`usuario_idUsuario` ASC),
  CONSTRAINT `fk_usuario_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `bdbanco`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdbanco`.`movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdbanco`.`movimiento` (
  `idMovimiento` INT(11) NOT NULL AUTO_INCREMENT,
  `Tipo` ENUM('ingreso', 'debito', 'transferencia') NULL DEFAULT NULL,
  `Fecha` DATETIME NULL DEFAULT NULL,
  `Entidad` VARCHAR(50) NULL DEFAULT NULL,
  `Concepto` VARCHAR(50) NULL DEFAULT NULL,
  `Cantidad` DOUBLE NULL DEFAULT NULL,
  `usuario_idUsuario` INT NOT NULL,
  `usuario_idUsuario1` INT NOT NULL,
  PRIMARY KEY (`idMovimiento`),
  INDEX `fk_movimiento_usuario1_idx` (`usuario_idUsuario` ASC),
  INDEX `fk_movimiento_usuario2_idx` (`usuario_idUsuario1` ASC),
  CONSTRAINT `fk_movimiento_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `bdbanco`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_usuario2`
    FOREIGN KEY (`usuario_idUsuario1`)
    REFERENCES `bdbanco`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdbanco`.`peticion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdbanco`.`peticion` (
  `idUsuario` INT(11) NOT NULL,
  `idUsuario1` INT(11) NOT NULL,
  INDEX `fk_peticion_usuario2_idx` (`idUsuario1` ASC),
  CONSTRAINT `fk_peticion_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bdbanco`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peticion_usuario2`
    FOREIGN KEY (`idUsuario1`)
    REFERENCES `bdbanco`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;